# After changing this file, check it on:
#   http://lint.travis-ci.org/

language: python
python:
 - 3.4
sudo: false
cache: pip
addons:
  apt:
    packages:
    - gir1.2-pango-1.0
    - gir1.2-gtk-3.0
    - xdg-utils
    - librsvg2-common
    - libglib2.0-dev
    - intltool
    # - python3-gobject Provided by python3-gi
    - python3-gi
    - python3-cairo
    - python3-gi-cairo
    - python3-bsddb3
    - python3-dev
    - python3-nose
    - python3-mock

before_install:
 - alias python='/usr/bin/python3'
 - pip3 install --upgrade pip
 - pip3 install --upgrade setuptools wheel nose coverage codecov

install:
 - travis_retry pip3 install --upgrade pillow pi
 - travis_retry pip3 install pyicu==1.8
 
 # - cd $TRAVIS_BUILD_DIR
 # $TRAVIS_BUILD_DIR is set to the location of the cloned repository:
 # for example: /home/travis/build/gramps-project/gramps
 - python3 setup.py build

before_script:
#    - sudo Xvfb :99 -ac &
#    - export DISPLAY=:99
 - mkdir -p ~/.gramps/grampsdb/

script:
 # --exclude=TestUser because of older version of mock
 #                    without configure_mock
 - nosetests3 --nologcapture --with-coverage --cover-package=gramps --exclude=TestcaseGenerator --exclude=vcard --exclude=merge_ref_test  --exclude=user_test gramps

after_success:
 - codecov

